Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:07:31
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
[30/Apr/2022 22:07:32] "GET /swagger HTTP/1.1" 200 1643
[30/Apr/2022 22:07:32] "GET /swagger?format=openapi HTTP/1.1" 200 35351
[30/Apr/2022 22:07:32] "GET /swagger?format=openapi HTTP/1.1" 200 35351
[code_25_get_access] 시간 : 2022-04-30 13:07:56.078832, UID : 61 Access토큰 발급
[30/Apr/2022 22:07:56] "POST /v1/user/signin HTTP/1.1" 200 687
Internal Server Error: /v1/review/like/5
Traceback (most recent call last):
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py", line 325, in reviewLike
    reviewQuery.like = reviewLike.append(flag)
AttributeError: 'function' object has no attribute 'append'
[30/Apr/2022 22:08:05] "PUT /v1/review/like/5 HTTP/1.1" 500 17152
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:08:39
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
[30/Apr/2022 22:08:42] "PUT /v1/review/like/5 HTTP/1.1" 200 86
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:09:15
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
Internal Server Error: /v1/review/like/5
Traceback (most recent call last):
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py", line 326, in reviewLike
    reviewQuery.like = temp.append(flag)
AttributeError: 'NoneType' object has no attribute 'append'
[30/Apr/2022 22:09:16] "PUT /v1/review/like/5 HTTP/1.1" 500 17146
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:09:36
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
None
Internal Server Error: /v1/review/like/5
Traceback (most recent call last):
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/hyeok/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py", line 327, in reviewLike
    reviewQuery.like = temp.append(flag)
AttributeError: 'NoneType' object has no attribute 'append'
[30/Apr/2022 22:09:36] "PUT /v1/review/like/5 HTTP/1.1" 500 17146
[]
[30/Apr/2022 22:09:54] "PUT /v1/review/like/5 HTTP/1.1" 200 86
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:10:51
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
[]
[61]
[30/Apr/2022 22:10:57] "PUT /v1/review/like/5 HTTP/1.1" 200 86
[code_25_get_access] 시간 : 2022-04-30 13:11:30.398069, UID : 68 Access토큰 발급
[30/Apr/2022 22:11:30] "POST /v1/user/signin HTTP/1.1" 200 701
[61]
[61, 68]
[30/Apr/2022 22:11:38] "PUT /v1/review/like/5 HTTP/1.1" 200 86
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:14:01
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
[30/Apr/2022 22:14:10] "GET /swagger HTTP/1.1" 200 1643
[30/Apr/2022 22:14:10] "GET /swagger?format=openapi HTTP/1.1" 200 35500
[30/Apr/2022 22:14:11] "GET /swagger?format=openapi HTTP/1.1" 200 35500
[code_25_get_access] 시간 : 2022-04-30 13:14:22.429683, UID : 68 Access토큰 발급
[30/Apr/2022 22:14:22] "POST /v1/user/signin HTTP/1.1" 200 701
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:15:13
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
[30/Apr/2022 22:15:13] "GET /swagger HTTP/1.1" 200 1643
[30/Apr/2022 22:15:14] "GET /swagger?format=openapi HTTP/1.1" 200 36104
[30/Apr/2022 22:15:14] "GET /swagger?format=openapi HTTP/1.1" 200 36104
[code_25_get_access] 시간 : 2022-04-30 13:15:37.898245, UID : 68 Access토큰 발급
[30/Apr/2022 22:15:37] "POST /v1/user/signin HTTP/1.1" 200 701
[30/Apr/2022 22:15:49] "DELETE /v1/review/like/5 HTTP/1.1" 200 69
/home/hyeok/dev/BookkyProject_BackEnd/bookky/views/reviewviews.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
bookky.AnyCommunity.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.
bookky.Review.like: (fields.E010) ArrayField default should be a callable instead of an instance so that it's not shared between all field instances.
	HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 2 issues (0 silenced).
April 30, 2022 - 22:28:55
Django version 4.0.3, using settings 'bookky_backend.settings'
Starting development server at http://0:8002/
Quit the server with CONTROL-C.
[30/Apr/2022 22:29:07] "GET /swagger HTTP/1.1" 200 1643
[30/Apr/2022 22:29:07] "GET /swagger?format=openapi HTTP/1.1" 200 36270
[30/Apr/2022 22:29:08] "GET /swagger?format=openapi HTTP/1.1" 200 36270
[code_25_get_access] 시간 : 2022-04-30 13:29:30.757047, UID : 61 Access토큰 발급
[30/Apr/2022 22:29:30] "POST /v1/user/signin HTTP/1.1" 200 687
[30/Apr/2022 22:29:43] "GET /v1/review/5 HTTP/1.1" 200 313
[30/Apr/2022 22:30:04] "GET /v1/books/reviews/3 HTTP/1.1" 200 524
